### ISSUE TITLE
CMAKE

### ISSUE THREAD

**Issue by atulkumar19** [ORNL-Fusion/GITR#101]
[CMakeError.log](https://github.com/ORNL-Fusion/GITR/files/7009025/CMakeError.log)
[CMakeOutput.log](https://github.com/ORNL-Fusion/GITR/files/7009026/CMakeOutput.log)
![screenshot](https://user-images.githubusercontent.com/28002496/129943192-526d5e6d-7f88-425e-baf1-2a0a15e6db3e.png)
Hi,
I am trying to install dev branch of GITR in Mac. Can you please tell me about " -Doption_name". I tried without selecting this option and I get an error (please see the attachment). Can you please help me with this?

Thanks,
Atul

**Comment by dlg0** [comment]
why do the build instructions recommend the `-S` and `-B` flags? that is just confusing and not the standard approach to building with cmake, i.e, 
```
git clone blah
cd source_dir_name
mkdir build
cd build
cmake ..
```

**Comment by atulkumar19** [comment]
Thanks David. It worked.
