### ISSUE TITLE
Compilation issue with CUDA enabled (USE_CUDA=1)

### ISSUE THREAD

**Issue by dhyan1272** [ORNL-Fusion/GITR#106]
GITR fails to compile with CUDA enabled and fails at the line
https://github.com/ORNL-Fusion/GITR/blob/dev/test_src/coulomb_tests.cpp#L505
```
GITR/test_src/coulomb_tests.cpp:505:9: error: ‘fsec0nc’  does not name a type; did you mean ‘fscanf’? 
```

**Comment by stonecoldhughes** [comment]
Thank you for identifying this issue! We are looking into it.
