### ISSUE TITLE
Cannot build with PARTICLESEEDS set to 0

### ISSUE THREAD

**Issue by hayes2419** [ORNL-Fusion/GITR#115]
problems stem from #else block in src/surface_model.cpp

**Comment by tyounkin** [comment]
The particle seeds option should always be set to 1. This is a deprecated option that should be removed.

**Comment by hayes2419** [comment]
@tyounkin can we just delete the #else blocks for the #if PARTICLESEEDS>0 if/else statements then?

**Comment by tyounkin** [comment]
Yes. You can create a branch and a draft PR if you like.
