### ISSUE TITLE
build time error on Fusiont5 with the dev branch

### ISSUE THREAD

**Issue by atulkumar19** [ORNL-Fusion/GITR#129]
When I pulled the recent commits from dev branch on fusiont5, I am encountering a build time error. Can someone please look into it? 

Thanks,
Atul

![build_time_error](https://user-images.githubusercontent.com/28002496/146649694-c67065b6-e347-4688-85ee-7c9b3f7275db.png)
l

**Comment by stonecoldhughes** [comment]
fixed!
