### ISSUE TITLE
build time error on fusiont6/t5

### ISSUE THREAD

**Issue by atulkumar19** [ORNL-Fusion/GITR#135]
While installing GITR, it stuck at "Built target netcdf-cxx4_download". Please also see the attached error file. Has anyone encountered this in past?

![buildtimeError](https://user-images.githubusercontent.com/28002496/153479943-7990f144-4ee1-4894-aa60-94c7d87ab7d1.png)
l

**Comment by stonecoldhughes** [comment]
Fixed!
