### ISSUE TITLE
error allocating managed memory: fusiont5

### ISSUE THREAD

**Issue by atulkumar19** [ORNL-Fusion/GITR#140]
While running GITR on fusiont5, I am getting a runtime error "error allocating managed memory". Please see the attached file.
![Screen Shot 2022-02-12 at 11 48 10 AM](https://user-images.githubusercontent.com/28002496/153720275-304dbc2e-928b-4c17-88fd-94c300328138.png)

**Comment by atulkumar19** [comment]
I am not sure if this is related to low disk space on fusiont5.

**Comment by stonecoldhughes** [comment]
fixed!
