### ISSUE TITLE
ERROR: Failed importing flags

### ISSUE THREAD

**Issue by aeiou6630** [ORNL-Fusion/GITR#26]
Hi,

I got a problem when executing the built GITR file for the example d3dTutorial. The Error reads:

`ERROR: Failed importing flags.USE_IONIZATION`

But since it's the first flag to import, I guess it's possible that it won't be able to import other flags as well. The full message shown was:

```
Program Name Is: ../../build/GITR
No Extra Command Line Argument Passed Other Than Program NameOpen configuration file input/gitrInput.cfg
Finished libconfig import  input/gitrInput.cfg
geometry.fileString = gitrD3DGeometry2DWringsPy.cfg
Open geometry file input/gitrD3DGeometry2DWringsPy.cfg
Finished libconfig import  input/gitrD3DGeometry2DWringsPy.cfg
Successfully staged input and geometry file
Checking compatibility of compile flags with input file
flags.USEIONIZATION = 0
flags.USERECOMBINATION = 0
flags.USEPERPDIFFUSION = 0
flags.USECOULOMBCOLLISIONS = 0
flags.USETHERMALFORCE = 0
flags.USESURFACEMODEL = 0
flags.USESHEATHEFIELD = 0
flags.BIASED_SURFACE = 0
flags.USEPRESHEATHEFIELD = 0
flags.BFIELD_INTERP = 2
flags.LC_INTERP = 0
flags.GENERATE_LC = 0
flags.EFIELD_INTERP = 0
flags.PRESHEATH_INTERP = 0
flags.DENSITY_INTERP = 0
flags.TEMP_INTERP = 0
flags.FLOWV_INTERP = 0
flags.GRADT_INTERP = 0
flags.ODEINT = 1
flags.FIXEDSEEDS = 1
flags.PARTICLESEEDS = 1
flags.GEOM_TRACE = 0
flags.GEOM_HASH = 1
flags.GEOM_HASH_SHEATH = 0
flags.PARTICLE_TRACKS = 1
flags.PARTICLE_SOURCE_SPACE = 0
flags.PARTICLE_SOURCE_ENERGY = 0
flags.PARTICLE_SOURCE_ANGLE = 0
flags.PARTICLE_SOURCE_FILE = 0
flags.SPECTROSCOPY = 2
flags.USE3DTETGEOM = 0
flags.USECYLSYMM = 0
flags.FLUX_EA = 0
flags.FORCE_EVAL = 0
ERROR: Failed importing flags.USE_IONIZATION
```

I guess it somehow suggested that the GITR file I `make` by "makeGITRmac.sh" was problematic. In fact, I got a lot of warning when making the GITR such as:

```
[  4%] Building CXX object CMakeFiles/YourLib.dir/src/EfieldInterp.cpp.o
cc1plus: warning: /home/fchang/softwares/Install/GITR/include/Boundary.h: not a directory
cc1plus: warning: /home/fchang/softwares/Install/GITR/include/Fields.h: not a directory
cc1plus: warning: /home/fchang/softwares/Install/GITR/include/Particle.h: not a directory
cc1plus: warning: /home/fchang/softwares/Install/GITR/include/Particles.h: not a directory
cc1plus: warning: /home/fchang/softwares/Install/GITR/include/Surfaces.h: not a directory
cc1plus: warning: /home/fchang/softwares/Install/GITR/include/array.h: not a directory
cc1plus: warning: /home/fchang/softwares/Install/GITR/include/boris.h: not a directory
cc1plus: warning: /home/fchang/softwares/Install/GITR/include/boundaryInit.h: not a directory
cc1plus: warning: /home/fchang/softwares/Install/GITR/include/coulombCollisions.h: not a directory
cc1plus: warning: /home/fchang/softwares/Install/GITR/include/crossFieldDiffusion.h: not a directory
cc1plus: warning: /home/fchang/softwares/Install/GITR/include/curandInitialize.h: not a directory
cc1plus: warning: /home/fchang/softwares/Install/GITR/include/curandInitialize2.h: not a directory
cc1plus: warning: /home/fchang/softwares/Install/GITR/include/device.h: not a directory
cc1plus: warning: /home/fchang/softwares/Install/GITR/include/fieldLineTrace.h: not a directory
cc1plus: warning: /home/fchang/softwares/Install/GITR/include/geometryCheck.h: not a directory
cc1plus: warning: /home/fchang/softwares/Install/GITR/include/hashGeom.h: not a directory
cc1plus: warning: /home/fchang/softwares/Install/GITR/include/hashGeomSheath.h: not a directory
cc1plus: warning: /home/fchang/softwares/Install/GITR/include/history.h: not a directory
cc1plus: warning: /home/fchang/softwares/Install/GITR/include/interpolate.h: not a directory
cc1plus: warning: /home/fchang/softwares/Install/GITR/include/ionize.h: not a directory
cc1plus: warning: /home/fchang/softwares/Install/GITR/include/managed_allocation.h: not a directory
cc1plus: warning: /home/fchang/softwares/Install/GITR/include/ompPrint.h: not a directory
cc1plus: warning: /home/fchang/softwares/Install/GITR/include/recombine.h: not a directory
cc1plus: warning: /home/fchang/softwares/Install/GITR/include/sortParticles.h: not a directory
cc1plus: warning: /home/fchang/softwares/Install/GITR/include/spectroscopy.h: not a directory
cc1plus: warning: /home/fchang/softwares/Install/GITR/include/surfaceModel.h: not a directory
cc1plus: warning: /home/fchang/softwares/Install/GITR/include/testIonize.h: not a directory
cc1plus: warning: /home/fchang/softwares/Install/GITR/include/testRoutine.h: not a directory
cc1plus: warning: /home/fchang/softwares/Install/GITR/include/testRoutineArray.h: not a directory
cc1plus: warning: /home/fchang/softwares/Install/GITR/include/testRoutineCuda.h: not a directory
cc1plus: warning: /home/fchang/softwares/Install/GITR/include/thermalForce.h: not a directory
cc1plus: warning: /home/fchang/softwares/Install/GITR/include/utils.h: not a directory
cc1plus: warning: /home/fchang/softwares/Install/GITR/test/tests_general.hpp: not a directory
```

Anyway, that's just my guess. I want to ask for suggestion on what might be the possible cause of this error. If that's not obvious, I wonder if there's a way, such as an error log or something showing more details about the error, that I can figure out the reason for the error.

My system is Ubuntu subsystem on a Windows 10 PC. I attach here the "makeGITRmac.sh" I used, and the full message shown when I used it to make GITR as a text file.

[makeGITRmac.sh.txt](https://github.com/ORNL-Fusion/GITR/files/4908525/makeGITRmac.sh.txt)
[Warning message when making GITR.txt](https://github.com/ORNL-Fusion/GITR/files/4908526/Warning.message.when.making.GITR.txt)

Thanks!

**Comment by kumargp** [comment]
This error means that entry is not found in gitrInput.cfg, which is inside the 'input' directory.
Copy the relevant 'input' directory in the working directory, or create a link to it.
The warnings you see are harmless. It just means that the files included as directories here https://github.com/ORNL-Fusion/GITR/blob/master/CMakeLists.txt#L21  is not valid.

**Comment by tyounkin** [comment]
@aeiou6630 well done on getting the code compiled! This error is part of the development to replace compile time flags. How to fix it:

1. Go to the gitrInput.cfg file you are using for the desired case.
2. Go to the bottom of the file and find the section flags = {...}
3. In the flags section paste USE_IONIZATION = 1;

This should resolve the error and should not have an impact on the other parts of the set-up of your case. This is my fault as I allowed an in-development feature to get into the master branch. Dont hesitate to post more issues or contact me in order to find out more about setting up a simulation! Thanks.

**Comment by aeiou6630** [comment]
Thanks for the reply from @kumargp and @tyounkin .

I successfully solved this problem by adding `USE_IONIZATION = 1;` and `FIXED_SEEDS = 1;` in the "gitrInput.cfg" file. At first glance, I thought they were already there, but later I found what had been there were `USEIONIZATION` and `FIXEDSEEDS` without the underlines.

Now the message shown on the window includes this:
`gitr flags 1`
I guess that means all the flags are successfully imported.

But later I got another error (I'm not sure if I should open a new issue for it. ) which said:
`ERROR: Failed importing backgroundPlasmaProfiles.Bfield.interpolation`

@tyounkin , I wonder if this is also related to the development you mentioned. If not, how can I check the cause of it? I attach the " ~/GITR/bulid/makeGITRmac.sh" and " ~/GITR/examples/d3dTutorial/input/gitrInput.cfg" as text files here.

[makeGITRmac.sh.txt](https://github.com/ORNL-Fusion/GITR/files/4915844/makeGITRmac.sh.txt)
[gitrInput.cfg.txt](https://github.com/ORNL-Fusion/GITR/files/4915846/gitrInput.cfg.txt)

Hope this is not a big problem. Thanks for maintaining and improving the code.

**Comment by aeiou6630** [comment]
Hi,

I guess the problem of not able to import "interpolation" is caused by improper setting in the "gitrInput.cfg". I assume I can run it normally if all the settings in the file are good. So I want to ask if there's an instruction or example about how to set parameters in the "gitrInput.cfg" file, including the data type and unit of each parameter. For example, is this "interpolation" an integer? What's the meaning of it?

Thanks!

**Comment by tyounkin** [comment]
@aeiou6630 Yes, you are correct. Integers set the dimensionality of the interpolation. We use, 0 (constant), 2 (2D in the x-z plane), and 3 (3D). 1D interpolation is not a valid option, but can be achieved by using 2D interpolation with no variance in one of the dimensions. For the problem you are encountering, you may need to paste the following options of interpolation, value, filename, and variable name into backgroundPlasmaProfiles.Bfield:

```
backgroundPlasmaProfiles = 
{
    Z = 1.0;
    amu = 2.0;
    biasPotential = 0.0;

    Bfield =
    {
          interpolation = 0; #0 is constant 1 is file and variable
          value = 1.234;
          filename = "../test/netcdf_file_py.nc";
          variable_name = "val";
          r = 2.0;
```

I should have an example with a readme which goes into greater detail on the input files. Let me take a look and I'll get back to you shortly. Thanks!

**Comment by aeiou6630** [comment]
Dear @tyounkin ,

Thanks! That solves the problem and I'm able to proceed to next step.

Unfortunately, I get another error which is not so straightforward to me. It's probably about how to use Netcdf-c or Netcdf-cxx correctly. The error says:

```
terminate called after throwing an instance of 'netCDF::exceptions::NcException'
  what():  Permission denied
file: ../../cxx4/ncFile.cpp  line:69
Aborted (core dumped)
```

I'm using netcdf-c-4.5.0 and netcdf-cxx4-4.3.0, which should be compatible with current version of GITR. I guess there are two possible cause of this error. One is that some code in GITR is modified and not compatible with the way of using netcdf. The other is that the way I install netcdf-c and netcdf-cxx4 on my computer is not correct. Therefore, I attach here the steps I take to install the GITR code from a blank Ubuntu system here:

[Install GITR_Ubuntu.txt](https://github.com/ORNL-Fusion/GITR/files/4959941/Install.GITR_Ubuntu.txt)

And I put the whole message shown when executing GITR here:

[Message when executing GITR.txt](https://github.com/ORNL-Fusion/GITR/files/4959943/Message.when.executing.GITR.txt)

I know this might take some time. Thanks for your help!

**Comment by tyounkin** [comment]
@aeiou6630 This error is occurring because GITR is attempting to write output to a folder which does not exist. This error should be alleviated by running 

```mkdir output```
Then running the code again. Let me know if that works!

**Comment by aeiou6630** [comment]
Thanks for your reply. That fixes the problem.
