### ISSUE TITLE
Parallel diffusion removed?

### ISSUE THREAD

**Issue by aeiou6630** [ORNL-Fusion/GITR#31]
Hi,

I'm trying to simulate impurity transport in a linear device. For a simple test, I try to simulate the particle parallel diffusion. 

I construct a rectangular box, apply magnetic field only in the z direction, assume homogeneous plasma (n=1e19, Te=10 and Ti=1), and inject 20 particles at the same location with velocity only in the z direction. But it turns out that their z(t) are exactly the same, so I think there's no parallel diffusion.

My question is how to turn on the parallel diffusion function. I find "USEPARDIFFUSION" variable in the "gitrInput.cfg" of d3dTutorial example, but not in the "makeGITRmac.sh" script. Is this function removed or can be achieved by other means?

BTW, what's the unit of the diffusion coefficient "Dperp"?

Thanks!

--
I attach the related files here:
[makeGITRmac.sh.txt](https://github.com/ORNL-Fusion/GITR/files/5250854/makeGITRmac.sh.txt)
[gitrD3DGeometry2DWringsPy.cfg.txt](https://github.com/ORNL-Fusion/GITR/files/5250855/gitrD3DGeometry2DWringsPy.cfg.txt)
[gitrInput.cfg.txt](https://github.com/ORNL-Fusion/GITR/files/5250927/gitrInput.cfg.txt)

**Comment by tyounkin** [comment]
@aeiou6630 parallel velocity diffusion in GITR is done by using the flags:
USECOULOMBCOLLISIONS=1
USEFRICTION=1
USEANGLESCATTERING=1
USEHEATING=1

Although friction, angle scattering, and heating are of different aspects of the coulomb collisions, they work together to produce a Maxwellian distribution.

The "USEPARDIFFUSION" was an experimental feature that attempted to simulate the velocity diffusion parallel to the magnetic field using a spatial diffusion. In your simulations it should be set to zero, and it should be removed from the code base.

The units for Dperp are meters squared per second.

**Comment by aeiou6630** [comment]
Got it. Thanks for your reply.
