### ISSUE TITLE
CUDA version/driver mismatch

### ISSUE THREAD

**Issue by stonecoldhughes** [ORNL-Fusion/GITR#37]
The CUDA runtime version is separate from the CUDA driver version, and only certain version ranges are compatible. Mismatches like this cause GITR to silently fail. Proposed solution: have the build system verify a working CUDA installation and warn the user of a CUDA runtime/driver mismatch.

**Comment by tyounkin** [comment]
@stonecoldhughes, here is the build file with options, etc (changed to text file): 
[makeGITRfusiont5_impacts.txt](https://github.com/ORNL-Fusion/GITR/files/5837658/makeGITRfusiont5_impacts.txt)

After building with these options, running the GITR executable from GITR/examples/impacts directory should reproduce the error.

**Comment by stonecoldhughes** [comment]
Updated CMake CUDA modules are now in place
