### ISSUE TITLE
compile error from boundaryInit.h

### ISSUE THREAD

**Issue by hayes2419** [ORNL-Fusion/GITR#38]
Line 127 in `boundaryInit.h` reads as `#elif USE_SURFACE_POTENTIAL >0`
This causes a compile issue (make sequence) `error: invalid token at start of a preprocessor expression`
Temp solution was to comment the line as `##elif USE_SURFACE_POTENTIAL >0`

Additionally, the following `#else` statement reads as `b.potential = 3.0*b.te;`
However, the 3.0 may be desired as a variable input rather than a hard-coded constant so that the potential well can be altered. Specifically, DIII-D users want this constant to be a variable.

**Comment by stonecoldhughes** [comment]
This is now resolved
