### ISSUE TITLE
GITR mac install env error

### ISSUE THREAD

**Issue by hayes2419** [ORNL-Fusion/GITR#4]
after running ./makeGITR.sh command, 
`../env.gpufusion.sh: line 2: module: command not found` 
error appears for lines 2 through 8 followed by 
`./makeGITR.sh: line 4: /Users/Alyssa/cmake/cmake-3.7.0-rc1-Linux-x86_64/bin/cmake: No such file or directory`

**Comment by tyounkin** [comment]
I've updated the documentation to point to the correct file for this. It shoule be ```cp makeGITRmac.sh build/```

**Comment by stonecoldhughes** [comment]
deprecated usage example
