### ISSUE TITLE
error: invalid token at start of a preprocessor expression

### ISSUE THREAD

**Issue by jguterl** [ORNL-Fusion/GITR#45]
[pc:build] >make
Scanning dependencies of target YourLib
[  4%] Building CXX object CMakeFiles/YourLib.dir/src/EfieldInterp.cpp.o
[  9%] Building CXX object CMakeFiles/YourLib.dir/src/Particle.cpp.o
[ 13%] Building CXX object CMakeFiles/YourLib.dir/src/flags.cpp.o
[ 18%] Building CXX object CMakeFiles/YourLib.dir/src/interp2d.cpp.o
[ 22%] Building CXX object CMakeFiles/YourLib.dir/src/setup.cpp.o
[ 27%] Building CXX object CMakeFiles/YourLib.dir/src/utils.cpp.o
/Users/guterl/Code/GITR/src/utils.cpp:580:29: error: invalid token at start of a preprocessor expression
  #if USE_SURFACE_POTENTIAL > 0
                            ^
1 error generated.
make[2]: *** [CMakeFiles/YourLib.dir/src/utils.cpp.o] Error 1
make[1]: *** [CMakeFiles/YourLib.dir/all] Error 2
make: *** [all] Error 2

**Comment by jguterl** [comment]
This means the USE_SURFACE_POTENTIAL is not evaluated at the compile time

**Comment by tyounkin** [comment]
To fix this, the following can be added to the makeGITRXXX.sh file

 -DUSE_SURFACE_POTENTIAL=0 \

**Comment by jguterl** [comment]
Yes. That works!
