### ISSUE TITLE
compile error branch constant_decay aa49401

### ISSUE THREAD

**Issue by jguterl** [ORNL-Fusion/GITR#48]
/Users/guterl/Code/GITR/src/gitr.cpp:4028:10: warning: expression result unused [-Wunused-value]
    for (tt; tt < nT; tt++) {
         ^~
/Users/guterl/Code/GITR/src/gitr.cpp:4481:65: error: use of undeclared identifier 'density_fraction'
               &closeGeom_sheath.front(), closestBoundaryIndex, density_fraction);
                                                                ^
1 warning and 1 error generated.

**Comment by tyounkin** [comment]
@jguterl, most likely I did not implement this for ALL available options in GITR. I know you are most likely using a 3D surface geometry. Can you paste the other build options you are using here? E.g., USEIONIZATION=, USECYLSYMM, USESHEATHEFIELD, etc. Thanks!

**Comment by jguterl** [comment]
#!/bin/bash
source ../env.mac.sh

cmake -DTHRUST_INCLUDE_DIR=$THRUST_DIR \
    -DCMAKE_C_COMPILER=/usr/local/opt/llvm/bin/clang \
    -DCMAKE_CXX_COMPILER=/usr/local/opt/llvm/bin/clang++ \
    -DCMAKE_CXX_FLAGS="-O3" \
    -DNETCDF_CXX_INCLUDE_DIR=$NETCDFCXX4INCLUDE \
    -DNETCDF_CXX_LIBRARY=$NETCDFLIB_CPP \
    -DNETCDF_DIR=$NETCDFDIR \
    -DNETCDF_INCLUDE_DIR=$NETCDFINCLUDE \
    -DNETCDF_LIBRARY=$NETCDFLIB \
    -DNETCDF_CXX_INCLUDE_DIR=$NETCDFCXX4INCLUDE \
    -DLIBCONFIGPP_INCLUDE_DIR=$LIBCONFIGPP_INCLUDE \
    -DUSE_CUDA=0 \
    -DUSE_MPI=0 \
    -DUSEIONIZATION=1 \
    -DUSERECOMBINATION=1 \
    -DUSEPERPDIFFUSION=0 \
    -DUSECOULOMBCOLLISIONS=0 \
    -DUSEFRICTION=0 \
    -DUSEANGLESCATTERING=0 \
    -DUSEHEATING=0 \
    -DUSETHERMALFORCE=0 \
    -DUSESURFACEMODEL=0 \
    -DUSE_SURFACE_POTENTIAL=0 \
    -DUSESHEATHEFIELD=0 \
    -DBIASED_SURFACE=0 \
    -DUSEPRESHEATHEFIELD=0 \
    -DBFIELD_INTERP=0 \
    -DLC_INTERP=0 \
    -DGENERATE_LC=0 \
    -DEFIELD_INTERP=0 \
    -DPRESHEATH_INTERP=0 \
    -DDENSITY_INTERP=0 \
    -DTEMP_INTERP=0 \
    -DFLOWV_INTERP=0 \
    -DGRADT_INTERP=0 \
    -DODEINT=0 \
    -DFIXEDSEEDS=0 \
    -DPARTICLESEEDS=1 \
    -DGEOM_TRACE=0 \
    -DGEOM_HASH=0 \
    -DGEOM_HASH_SHEATH=0 \
    -DPARTICLE_TRACKS=1 \
    -DPARTICLE_SOURCE_SPACE=0 \
    -DPARTICLE_SOURCE_ENERGY=0 \
    -DPARTICLE_SOURCE_ANGLE=0 \
    -DPARTICLE_SOURCE_FILE=0 \
    -DSPECTROSCOPY=2 \
    -DUSE3DTETGEOM=0 \
    -DUSECYLSYMM=0 \
    -DUSEFIELDALIGNEDVALUES=0 \
    -DFLUX_EA=0 \
    -DFORCE_EVAL=0 \
    -DUSE_SORT=0 \
    -DCHECK_COMPATIBILITY=1 \
    ..
    #-DCMAKE_CXX_FLAGS="-g -Wall -Wextra -Wpedantic -Wconversion -Wno-unused-parameter -Wno-float-conversion -Wno-unused-variable -Wno-unused-but-set-variable" \

**Comment by tyounkin** [comment]
@jguterl I just pushed an update to the constant_decay branch fixing the compile error.

However, in this quickly developed branch, the analytic electric field model E = (potential/lambda)*exp(-z/lambda) and ne =(1-exp(-z/lambda))*ne_at_sheath_entrance are BOTH controlled (turned on or off) by the USESHEATHEFIELD compile time variable. With your current options, neither the analytic sheath E-field or the adjustment of electron density are used. With USESHEATHEFIELD=1, both will be used. Let me know if you need more functionality than this.

**Comment by jguterl** [comment]
Ok. Thanks. It is just that the option setup at compiled time is a
confusing to me. It should work.

**Comment by jguterl** [comment]
What is the way to recompile the code when needed? Going to the build folder and change manually the option?

**Comment by tyounkin** [comment]
@jguterl Yes. Manually change the option in the makeGITRxxx.sh file. In some cases, in the build folder the CMakeCache, Makefile, CMakeFiles folder that are produced may need to be deleted. This will ensure the options and build process starts completely from the beginning. I use a bash script for this:

#!/bin/bash
 rm -r CMakeFiles
 rm CMakeCache.txt
 rm cmake_install.cmake
 rm Makefile
 rm GITR
 rm CTestTestfile.cmake
 rm atomic_tests
 rm coulomb_tests
 rm field_tests
 rm libYourlib.a
 rm tests

**Comment by jguterl** [comment]
I do not understand why the following is not

**Comment by jguterl** [comment]
I do not understand why I am running into a compile error:
-- DirDefs: USE_PARALLELHAS_NETCDF_PAR_HUSE_CUDA=0USE_MPI=0USEIONIZATION=0USERECOMBINATION=0USEPERPDIFFUSION=0USECOULOMBCOLLISIONS=0USEFRICTION=0USEANGLESCATTERING=0USEHEATING=0USETHERMALFORCE=0USESURFACEMODEL=0USESHEATHEFIELD=1BIASED_SURFACE=0USE_SURFACE_POTENTIAL=0USEPRESHEATHEFIELD=0BFIELD_INTERP=0LC_INTERP=0GENERATE_LC=0EFIELD_INTERP=0PRESHEATH_INTERP=0DENSITY_INTERP=0TEMP_INTERP=0FLOWV_INTERP=0GRADT_INTERP=0ODEINT=1FIXEDSEEDS=0PARTICLESEEDS=1GEOM_TRACE=0GEOM_HASH=0GEOM_HASH_SHEATH=0PARTICLE_TRACKS=1PARTICLE_SOURCE=PARTICLE_SOURCE_SPACE=0PARTICLE_SOURCE_ENERGY=0PARTICLE_SOURCE_ANGLE=0PARTICLE_SOURCE_FILE=0SPECTROSCOPY=2USE3DTETGEOM=0USECYLSYMM=0USEFIELDALIGNEDVALUES=0FLUX_EA=1FORCE_EVAL=0USE_SORT=0CHECK_COMPATIBILITY=1
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/guterl/Code/GITR/build
Scanning dependencies of target YourLib
[  4%] Building CXX object CMakeFiles/YourLib.dir/src/EfieldInterp.cpp.o
[  9%] Building CXX object CMakeFiles/YourLib.dir/src/Particle.cpp.o
[ 13%] Building CXX object CMakeFiles/YourLib.dir/src/flags.cpp.o
[ 18%] Building CXX object CMakeFiles/YourLib.dir/src/interp2d.cpp.o
[ 22%] Building CXX object CMakeFiles/YourLib.dir/src/setup.cpp.o
[ 27%] Building CXX object CMakeFiles/YourLib.dir/src/utils.cpp.o
/Users/guterl/Code/GITR/src/utils.cpp:975:1: warning: non-void function does not return a value in all control paths [-Wreturn-type]
}
^
1 warning generated.
[ 31%] Building CXX object CMakeFiles/YourLib.dir/test/tests_general.cpp.o
[ 36%] Linking CXX static library libYourLib.a
[ 36%] Built target YourLib
Scanning dependencies of target field_tests
[ 40%] Building CXX object CMakeFiles/field_tests.dir/test/field_tests.cpp.o
[ 45%] Linking CXX executable field_tests
[ 45%] Built target field_tests
Scanning dependencies of target coulomb_tests
[ 50%] Building CXX object CMakeFiles/coulomb_tests.dir/test/coulomb_tests.cpp.o
In file included from /Users/guterl/Code/GITR/test/coulomb_tests.cpp:2:
In file included from /Users/guterl/Code/GITR/include/coulombCollisions.h:15:
/Users/guterl/Code/GITR/include/boris.h:1026:15: error: no matching function for call to 'getE'
    minDist = getE(r[0],r[1],r[2],E,boundaryVector,nLines);
              ^~~~
/Users/guterl/Code/GITR/include/boris.h:91:7: note: candidate function not viable: requires 15 arguments, but 6 were provided
float getE ( float x0, float y, float z, float E[], Boundary *boundaryVector, int nLines,
      ^
/Users/guterl/Code/GITR/include/boris.h:1082:15: error: no matching function for call to 'getE'
    minDist = getE(r2[0],r2[1],r2[2],E,boundaryVector,nLines);
              ^~~~
/Users/guterl/Code/GITR/include/boris.h:91:7: note: candidate function not viable: requires 15 arguments, but 6 were provided
float getE ( float x0, float y, float z, float E[], Boundary *boundaryVector, int nLines,
      ^
/Users/guterl/Code/GITR/include/boris.h:1138:15: error: no matching function for call to 'getE'
    minDist = getE(r3[0],r3[1],r3[2],E,boundaryVector,nLines);
              ^~~~
/Users/guterl/Code/GITR/include/boris.h:91:7: note: candidate function not viable: requires 15 arguments, but 6 were provided
float getE ( float x0, float y, float z, float E[], Boundary *boundaryVector, int nLines,
      ^
/Users/guterl/Code/GITR/include/boris.h:1192:12: error: no matching function for call to 'getE'
        minDist = getE(r4[0],r4[1],r4[2],E,boundaryVector,nLines);
                  ^~~~
/Users/guterl/Code/GITR/include/boris.h:91:7: note: candidate function not viable: requires 15 arguments, but 6 were provided
float getE ( float x0, float y, float z, float E[], Boundary *boundaryVector, int nLines,
      ^
4 errors generated.
make[2]: *** [CMakeFiles/coulomb_tests.dir/test/coulomb_tests.cpp.o] Error 1
make[1]: *** [CMakeFiles/coulomb_tests.dir/all] Error 2
make: *** [all] Error 2

**Comment by tyounkin** [comment]
@jguterl looks like you changed the ODEINT from 0 to 1. ODEINT=0 uses the boris integration scheme. ODEINT=1 uses RK4 integration, but it looks like some aspects of the getE function has been changed without the RK4 integrator being properly updated.

**Comment by jguterl** [comment]
Ok. Thanks. Make sense...
