### ISSUE TITLE
d3dTutorial example not working

### ISSUE THREAD

**Issue by jlore** [ORNL-Fusion/GITR#5]
I have built the latest master branch commit (13d7de1bea8d36b79f8836cd594a90a5c38cb053), but cannot run the d3dTutorial example.

relevant output:

reading  input/bFromGfile.nc
node 0Bfield at 5.5 -4 -0.622729 1.35806 -0.320645
Start of geometry import
Got geom setting
Just read nLines 66
Number of Geometric Objects To Load: 66
Boundary import routine 67
Doesn't Exists
 Successfully Created 
terminate called after throwing an instance of 'libconfig::SettingNotFoundException'
  what():  SettingNotFoundException

**Comment by jlore** [comment]
Now on 248e25d0b92862eaea48a13e4b12a07bd9845c4b

Got further, but got opaque core dump

particle file import done
Tracks subsample factor imported 1
History array length 10001000
Beginning random number seeds
Random Number Initialize time for node 0          is  0.008 (secs) 
Initialize time for node 0          is  0.826 (secs) 
diagnostics.leakZ = 0
Flow velocities 0 0 -2000
Starting main loop
Floating point exception (core dumped)

**Comment by jlore** [comment]
Debug info:
```

Thread 110 "GITR" received signal SIGFPE, Arithmetic exception.
[Switching to Thread 0x7fff824a1700 (LWP 26861)]
0x0000000000427a8b in Boundary::getSurfaceNormal (x=-1.08763587, y=0.928432822, B=<synthetic pointer>, this=<optimized out>)
    at /home/jjl/GITR/include/Boundary.h:120
120             float perpSlope = -sgn(slope_dzdx)/abs(slope_dzdx);
(gdb) bt
#0  0x0000000000427a8b in Boundary::getSurfaceNormal (x=-1.08763587, y=0.928432822, B=<synthetic pointer>, this=<optimized out>)
    at /home/jjl/GITR/include/Boundary.h:120
#1  geometry_check::operator() (this=0x7fffffff99a0, indx=969) at /home/jjl/GITR/include/geometryCheck.h:715
#2  0x000000000041f930 in thrust::detail::wrapped_function<geometry_check, void>::operator()<unsigned long> (x=<optimized out>, this=<optimized out>)
    at /usr/include/thrust/detail/function.h:60
#3  thrust::system::omp::detail::for_each_n<thrust::system::omp::detail::par_t, thrust::counting_iterator<unsigned long, thrust::use_default, thrust::use_default, thrust::use_default>, long long, geometry_check> () at /usr/include/thrust/system/omp/detail/for_each.inl:74
#4  0x00007ffff67c143e in ?? () from /usr/lib/x86_64-linux-gnu/libgomp.so.1
#5  0x00007ffff63866ba in start_thread (arg=0x7fff824a1700) at pthread_create.c:333
#6  0x00007ffff60bc41d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109
```

**Comment by tyounkin** [comment]
Let me put a fix in for this. It surprises me that this has not caused problems sooner than this.

**Comment by tyounkin** [comment]
@jlore do you have something set to catch such exceptions? I didn't think gcc caught divide by zero by default. I think I'd like to go through the code and address any/all such cases.

**Comment by jlore** [comment]
I didn't do anything special, might be version dependent.

**Comment by jlore** [comment]
Looks like flags were 
-g -fopenmp -O3 -Wno-c++11-narrowing -g   -x c++ -DTHRUST_DEVICE_SYSTEM=THRUST_DEVICE_SYSTEM_OMP -std=gnu++14

**Comment by jlore** [comment]
Works now with latest commit
