### ISSUE TITLE
better quickstart guide

### ISSUE THREAD

**Issue by dlg0** [ORNL-Fusion/GITR#50]
the quickstart should be code, not paragraphs of words

**Comment by dlg0** [comment]
i also note that the present readme is inconsistent with the actual directory structure and file locations in the repo

**Comment by jguterl** [comment]
I have started something like that for myself:https://hackmd.io/@djtyW4n0TgS3u4YCdulk-w/SyA_-ou1u

**Comment by tyounkin** [comment]
@dlg0 what do you mean it should be code? Like executable commands?

**Comment by dlg0** [comment]
Yes, a series of commands that can be executed from the command line. If you have CI setup, then the recipe to run the CI is a good example.

**Comment by stonecoldhughes** [comment]
README has been updated
