### ISSUE TITLE
bfield definition

### ISSUE THREAD

**Issue by jguterl** [ORNL-Fusion/GITR#61]
backgroundPlasmaProfiles =
{
	Z = 1;
	amu = 2.0;

	Bfield = {
    r = 0.0;
    z = -0.07852386758062718;
    t = 2.2486293607929655;
    rString = "r";
    zString = "z";
    yString = "t";
    }
};

-> ERROR: Failed importing backgroundPlasmaProfiles.Bfield.y

**Comment by tyounkin** [comment]
@jguterl in GITR coordinates, in many cases r and x are interchanged as some cases are in cylindrical coordinates and some are in cartesian. The same goes for y and t. z is always z. So in this case, your Bfield coordinates should be r,z,y. This should be unified to a consistent convention throughout inputs and code structure.
