### ISSUE TITLE
Catch2 for code testing purposes needs to be added to code and CMakeLists

### ISSUE THREAD

**Issue by tyounkin** [ORNL-Fusion/GITR#8]
Headers from here https://github.com/catchorg/Catch2 need to be downloaded.
A main program is then compiled with testing

**Comment by dlg0** [comment]
@grahamlopez would be proud.

**Comment by tyounkin** [comment]
What good would I be if I didn't apply all the REAL coding things I learn from @grahamlopez and @bmcdanie?

**Comment by grahamlopez** [comment]
:) :100:
